# scons.args: &scons
#     scons_arg:
#       - '--strict'

# ------ nano ------
nano:
  kconfig:
    - CONFIG_RT_USING_NANO=y
# ------ peripheral ------
peripheral.lcd:
  kconfig:
    - CONFIG_BSP_USING_SPI_LCD=y
    - CONFIG_BSP_USING_LCD_SAMPLE=y
    - CONFIG_BSP_USING_LCD_QRCODE=y
peripheral.sdcard-fatfs:
  kconfig:
    - CONFIG_BSP_USING_FS=y
    - CONFIG_BSP_USING_SDCARD_FATFS=y
# ------ rtduino ------
rtduino.adafruit-aht10:
  kconfig:
    - CONFIG_BSP_USING_SPI_LCD=y
    - CONFIG_BSP_USING_LCD_SAMPLE=y
    - CONFIG_BSP_USING_LCD_QRCODE=y
rtduino.adafruit-gfx:
  kconfig:
    - CONFIG_BSP_USING_ARDUINO=y
    - CONFIG_BSP_USING_ARDUINO_ST7789=y
    - CONFIG_BSP_USING_ARDUINO_ST7789_ADAFRUIT_GFX=y
    - CONFIG_BSP_USING_ARDUINO_ST7789_ADAFRUIT_GFX_DEMO=y
rtduino.tft-espi:
  kconfig:
    - CONFIG_BSP_USING_ARDUINO=y
    - CONFIG_BSP_USING_ARDUINO_ST7789=y
    - CONFIG_BSP_USING_ARDUINO_ST7789_TFT_ESPI=y
    - CONFIG_BSP_USING_ARDUINO_ST7789_TFT_ESPI_DEMO=y
# ------ lvgl ------
lvgl.v8.3-lastest:
  kconfig:
    - CONFIG_BSP_USING_LVGL=y
    - CONFIG_BSP_USING_LVGL_DEMO=y
    - CONFIG_PKG_LVGL_USING_V8_3_LATEST=y
lvgl.v8.3.11:
  kconfig:
    - CONFIG_BSP_USING_LVGL=y
    - CONFIG_BSP_USING_LVGL_DEMO=y
    - CONFIG_PKG_LVGL_USING_V080311=y
lvgl.v8.4-lastest:
  kconfig:
    - CONFIG_BSP_USING_LVGL=y
    - CONFIG_BSP_USING_LVGL_DEMO=y
    - CONFIG_PKG_LVGL_USING_V8_4_LATEST=y